; This file was auto-generated by drush make and then slightly modified manually
core = 6.x

api = 2
projects[drupal][version] = "6.28"

; Modules
projects[views_bulk_operations][version] = "1.13"

projects[admin_menu][version] = "1.8"

projects[advagg][version] = "1.9"

projects[advanced_help][version] = "1.2"

projects[backup_migrate][version] = "2.6"

projects[service_links][version] = "2.1"

projects[bueditor][version] = "2.7"

projects[calendar][version] = "2.4"

projects[checkbox_validate][version] = "2.1"

projects[codefilter][version] = "1.0"

projects[comment_driven][version] = "1.0-alpha3"
projects[comment_driven][patches][] = "http://drupalnorge.no/patches/comment_driven-819950.patch"

projects[cck][version] = "2.9"

projects[css_gzip][version] = "1.3"

projects[custom_breadcrumbs][version] = "1.5"

projects[date][version] = "2.9"

projects[devel][version] = "1.27"

projects[diff][version] = "2.3"

projects[driven][version] = "1.0-alpha3"

projects[email][version] = "1.4"

projects[filefield][version] = "3.10"

projects[google_analytics][version] = "3.5"

projects[honeypot][version] = "1.13"

projects[imageapi][version] = "1.10"

projects[imagecache][version] = "2.0-rc1"

projects[imagefield][version] = "3.10"

projects[imce][version] = "2.4"

projects[javascript_aggregator][version] = "1.6"

projects[jquery_media][version] = "1.3"

projects[jquery_ui][version] = "1.5"

projects[jquery_update][version] = "2.0-alpha1"

projects[l10n_update][version] = "1.0-beta3"

projects[libraries][version] = "1.0"

projects[link][version] = "2.9"

projects[mollom][version] = "1.16"

projects[path_redirect][version] = "1.0-rc2"

projects[pathauto][version] = "1.6"

projects[poormanscron][version] = "2.2"

projects[prepopulate][version] = "2.2"

projects[rules][version] = "1.5"

projects[signup][version] = "1.0"

projects[subscriptions][version] = "1.5"

projects[superfish][version] = "1.8"

projects[tagadelic][version] = "1.3"

projects[token][version] = "1.19"

projects[transliteration][version] = "3.1"

projects[upgrade_status][version] = "1.1"

projects[urllist][version] = "1.0"

projects[vertical_tabs][version] = "1.0-rc2"

projects[views][version] = "2.16"

projects[views_slideshow][version] = "2.4"

projects[views_slideshow_ddblock][version] = "1.1"

projects[xmlsitemap][version] = "1.2"

; Themes
projects[adaptivetheme][version] = "2.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[dnmagazine][download][type] = ""
projects[dnmagazine][download][url] = ""
projects[dnmagazine][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[drupalnorge6][download][type] = ""
projects[drupalnorge6][download][url] = ""
projects[drupalnorge6][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = "get"
libraries[superfish][download][url] = "http://dl.dropbox.com/u/22795799/superfish-library-for-drupal-v1.zip"
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

